### ISSUE TITLE
Login Activity wrong

### ISSUE THREAD

**Issue by qazwsdc** [sanzeeb3/wp-force-logout#1]
User has already logged in.But the login activity is still show offline....
My wordpress version is 5.0

**Comment by sanzeeb3** [comment]
The user might not be active. The user might just need to refresh.

**Comment by qazwsdc** [comment]
But my own admin account is also show offline.I am obviously logged in.

**Comment by sanzeeb3** [comment]
Sad to hear that. Could you please share more details of your system environments. Also, if possible, security, cache, or related plugins activated?

**Comment by qazwsdc** [comment]
I have installed "inactive logout" plugin but I already delete it right now.My environments is normal.Nothing special.Just a personal website.
I don't know how I can help you debug this.Maybe some files share to you?

**Comment by sanzeeb3** [comment]
Closed. Sadly, I could not replicate this across different environments. Might be plugin conflicts.
