### ISSUE TITLE
Errors with Ultimate Members plugin user roles

### ISSUE THREAD

**Issue by sanzeeb3** [sanzeeb3/wp-force-logout#19]
Ultimate Members administrator user roles are getting this error:

> Fatal error: Uncaught Exception: You donot have enough permission to perform this action in /autoinstalator/Adz_201008/wp-content/plugins/wp-force-logout/includes/class-wp-force-logout-process.php:304 Stack trace: #0 /autoinstalator/Adz_201008/wp-includes/class-wp-hook.php(287): WP_Force_Logout_Process->trigger_query_actions('') #1 /autoinstalator/Adz_201008/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #2 /autoinstalator/Adz_201008/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 /autoinstalator/Adz_201008/wp-admin/admin.php(367): do_action('load-users.php') #4 /autoinstalator/Adz_201008/wp-admin/users.php(11): require_once('/autoinstalator...') #5 {main} thrown in /autoinstalator/Adz_201008/wp-content/plugins/wp-force-logout/includes/class-wp-force-logout-process.php on line 304

Basically, the error should only appear if the user currently logged in does not have the capability to edit users.
https://github.com/sanzeeb3/wp-force-logout/blob/c1424ebe35637a8e6b4ef22ae09ac7376b7eaaaa/includes/class-wp-force-logout-process.php#L303

**Comment by Norman999** [comment]
I checked:
![Firefox_Screenshot_2020-10-14T12-52-30 698Z](https://user-images.githubusercontent.com/33767699/96003386-77754c00-0e3a-11eb-8727-fe1b88f14718.png)
and role with Ultimate Member:
![Firefox_Screenshot_2020-10-14T12-52-53 309Z](https://user-images.githubusercontent.com/33767699/96003475-8b20b280-0e3a-11eb-92ec-2673652d11f1.png)
Thanks for showing interest!

**Comment by sanzeeb3** [comment]
@Norman999 that is not correct. Please see the changes you'll need to make: https://github.com/sanzeeb3/wp-force-logout/commit/aa2542633efdc74cf1e64d1f8a3f58e12da47b06. This is also going to be fixed on the next version. I hope this helps!
