### ISSUE TITLE
login activity status still wrong in brand new env.

### ISSUE THREAD

**Issue by qazwsdc** [sanzeeb3/wp-force-logout#2]
Hi,
I’m very interested in your plugins.Today I make a brand new environment and install wordpress 5.0.3 from start.All the environment is new.No other plugins.Unfortunately,the login activity status still wrong.
All users show offline.My own admin account is also show offline.I am obviously logged in.
I think there is must a bug...

**Comment by sanzeeb3** [comment]
@qazwsdc When you get a chance, can you please contact me at sanzeeb.aryal@gmail.com? I might need further more information to look into the issue.

**Comment by qazwsdc** [comment]
Sure.I have sent you an email

**Comment by sanzeeb3** [comment]
Thanks for the details. I see the issue with timezone. If you set **Settings->General->Time Zone** to UTC, it works as expected. The fix will be available soon. Stay updated!

**Comment by sanzeeb3** [comment]
Fixed: 61cac444aaa76a69bfd99e7c59df98dedbb5e1ac

**Comment by qazwsdc** [comment]
Oh haha.....  Cool!!!
Love you guys
